### ISSUE TITLE
Add License for 1.16.2/1.16.3

### ISSUE THREAD

**Issue by Sindarin27** [minecraftabnormals/Atmospheric#54]
Forge mods on the newest versions require a license file. It appears this is currently the only required change to make this mod work on these versions.

**Comment by bageldotjpg** [comment]
World generation was rewritten for 1.16.2+, so adding this will not make it work on 1.16.2. Forge has not quite adapted to the world gen changes yet, so a 1.16.2 is not viable without losing a lot of content/generation.
