### ISSUE TITLE
Bagel is an asshole

### ISSUE THREAD

**Issue by ilija04** [minecraftabnormals/Atmospheric#64]
How dare you ban me from the MCA Discord? I'll show you motherfucker, for banning me with no reason!

**Comment by fivelol** [comment]
How dare you ban me from the MCA Discord? I'll show you motherfucker, for banning me with no reason!

**Comment by bageldotjpg** [comment]
> no reason
we had very many reasons, you attacked people, you were rude, and you had no respect for anyone.
this is proven by this post right here.
all the moderators agreed on your ban and several members of the community were insanely uncomfortable around you

**Comment by Epic312** [comment]
i'm glad i wasn't drinking anything when i saw this, otherwise i would've spat it out

**Comment by bageldotjpg** [comment]
top 10 awesome  github moments

**Comment by ShockMicro** [comment]
wholesome 100 keanu chungus github momentum

**Comment by Epic312** [comment]
the color code for ilija's rage at team abnormals is #D73A49

**Comment by c0d3break3r** [comment]
i think it's more #BF3441

**Comment by Bobisnotap** [comment]
aeiou

**Comment by TurtlemanGO** [comment]
Ilija04 likes the color #4A412A (Pantone 448 C)

**Comment by AncientPenguin2** [comment]
ilija is about to send one hell of a hex code.
