### ISSUE TITLE
Yucca chest recipe creates vanilla chest

### ISSUE THREAD

**Issue by CoruscareGames** [minecraftabnormals/Atmospheric#68]
This appears to be the issue as of the most recent 1.16.1 versions of Quark and Atmospheric. JEI lists the Yucca chest recipe, but the resulting chest is a regular vanilla chest. As a side note this also is the case for logs of any modded wood resulting in 4 vanilla chests and not the chests of the wood I used to craft it, but that's less urgent IMO.

**Comment by bageldotjpg** [comment]
Unfortunately this can't be fixed at the moment, I'd recommend using the mod Polymorph for the time being.
